apiVersion: v1
kind: Service
metadata:
  name: serviceforapp

spec:
  ports:
    - port: 80
      targetPort: bookappport # or 8080
      protocol: TCP

  selector:
      app: bookapp
  type: LoadBalancer